#!/usr/bin/env bash

COMMIT_MSG=$(git log -1 --pretty=%B)

if echo "$COMMIT_MSG" | grep -qE '^(feat|fix|docs|chore|style|refactor|test)\:(.*)+$'; then
  echo "Commit message follows convention."
else
  echo "🚫 ERROR: Commit message '$COMMIT_MSG' does not follow convention. Use 'feat:', 'fix:', etc."
  echo "chore: description your commit"
  exit 1
fi