#!/usr/bin/env bash

BRANCH_NAME=$(git rev-parse --abbrev-ref HEAD)

if echo "$BRANCH_NAME" | grep -qE '^(feature|bugfix|release|hotfix|refactor|test)\/.*'; then
  echo "✅ Valid branch name: $BRANCH_NAME"
else
  echo "🚫 The branch name '$BRANCH_NAME' does not follow the Gitflow standard."
  echo "Valid example: feature/new-functionality"
  exit 1
fi
