#!/bin/sh
. "$(dirname "$0")/_/husky.sh"

echo "Running pre-commit..."

BRANCH_NAME=$(git rev-parse --abbrev-ref HEAD)

if echo "$BRANCH_NAME" | grep -qE '^(feature|bugfix|release|hotfix|refactor)\/[a-z0-9-]+$'; then
  echo "✅ Valid branch name: $BRANCH_NAME"
else
  echo "🚫 The branch name '$BRANCH_NAME' does not follow the Gitflow standard."
  echo "Valid example: feature/new-functionality"
  exit 1
fi

# shellcheck disable=SC2164
cd app

echo "Running lint fix..."
npm run lint:fix

echo "Running format fix..."
npm run format:fix

# shellcheck disable=SC2103
cd ..

if [ -n "$(git status --porcelain)" ]; then
  echo "✅ Changes detected after formatting, adding to commit"
  git add .
  echo "✅ Changes added to the commit"
else
  echo "✅ No changes to add"
fi
