#!/bin/bash

BRANCH_NAME=$(git rev-parse --abbrev-ref HEAD)

# shellcheck disable=SC3010
if [[ ! "$BRANCH_NAME" =~ ^(feature|bugfix|release|hotfix)\/[a-z0-9-]+$ ]]; then
  echo "🚫 The branch name '$BRANCH_NAME' does not follow the Gitflow standard."
  echo "Valid example: feature/new-functionality"
  exit 1
else
  echo "The branch name '$BRANCH_NAME' does follow the Gitflow standard."
  exit 0
fi
