#!/bin/sh
. "$(dirname "$0")/_/husky.sh"

echo "Running pre-commit..."

# shellcheck disable=SC2164
cd app

echo "Running lint fix..."
npm run lint:fix

echo "Running format fix..."
npm run format:fix

# shellcheck disable=SC2103
cd ..

if [ -n "$(git status --porcelain)" ]; then
  echo "Changes detected after formatting, adding to commit"
  git add .
  echo "Changes added to the commit"
else
  echo "No changes to add"
fi
