name: CI - Create Release

on:
  pull_request:
    types:
      - closed

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  tag:
    if: contains(github.head_ref, 'release/') && contains(github.base_ref, 'main') && github.event.action == 'closed' && github.event.pull_request.merged == true
    runs-on: ubuntu-latest
    outputs:
      tag: ${{ steps.tag.outputs.tag }}
    steps:
      - name: Extract branch tag
        id: tag
        run: |
          BRANCH=${{ github.head_ref }}
          TAG="${BRANCH//release\//}"
          echo $TAG
          echo "tag=$TAG" >> $GITHUB_OUTPUT
  release:
    needs:
      - tag
    runs-on: ubuntu-latest
    env:
      TAG: ${{ needs.TAG.outputs.tag }}
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Push Tag
        uses: mathieudutour/github-tag-action@v6.2
        with:
          github_token: ${{ secrets.GH_PAT }}

      - name: Create Release
        uses: softprops/action-gh-release@v2.2.0
        with:
          name: v${{ env.TAG }}
          tag_name: v${{ env.TAG }}
          token: ${{ secrets.GH_PAT }}
          generate_release_notes: true