name: Gitflow Workflow

on:
  push:
    branches:
      - main
      - develop
      - "feature/*"
      - "hotfix/*"

permissions:
  contents: write
  pull-requests: write

jobs:
  gitflow:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Authenticate GitHub CLI
        run: echo "${{ secrets.GH_PAT }}" | gh auth login --with-token

      # Sync main to develop
      - name: Create Pull Request for Main to Develop
        if: startsWith(github.ref, 'refs/heads/main')
        run: |
            gh pr create \
               --base develop \
               --head main \
               --title "Sync main to develop" \
               --body "Automated Pull Request to sync changes from 'main' to 'develop'."

      # Feature to Develop
      - name: Create Pull Request for Feature to Develop
        if: startsWith(github.ref, 'refs/heads/feature/')
        run: |
          # Check if a PR already exists
          if gh pr list --base develop --head ${{ github.ref_name }} --state open --json id | jq '.[].id' > /dev/null; then
            echo "A Pull Request from '${{ github.ref_name }}' to 'develop' already exists. Skipping."
          else
            gh pr create \
              --base develop \
              --head ${{ github.ref_name }} \
              --title "Feature: Merge ${{ github.ref_name }} into Develop" \
              --body "This Pull Request merges the feature branch '${{ github.ref_name }}' into 'develop'."
          fi

      # Hotfix to Main and Develop
      - name: Create Pull Request for Hotfix
        if: startsWith(github.ref, 'refs/heads/hotfix/')
        run: |
          # PR for hotfix to main
          gh pr create \
              --base main \
              --head ${{ github.ref_name }} \
              --title "Hotfix: Merge ${{ github.ref_name }} into Main" \
              --body "This PR fixes critical issues in production."
        

          # PR for hotfix to develop
          gh pr create \
              --base develop \
              --head ${{ github.ref_name }} \
              --title "Hotfix: Sync ${{ github.ref_name }} with Develop" \
              --body "This PR ensures hotfix changes are merged into 'develop'."