name: Gitflow Workflow

on:
  push:
    branches:
      - main
      - "feature/*"
      - "hotfix/*"

permissions:
  contents: write
  pull-requests: write

jobs:
  gitflow:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Authenticate GitHub CLI
        run: echo "${{ secrets.GH_PAT }}" | gh auth login --with-token

      # Sync main to develop
      - name: Create and Merge Pull Request for Main to Develop
        if: github.ref_name && github.ref_name == 'main'
        run: |
          # Extract branch name
          MAIN_BRANCH=$(echo "${{ github.ref }}" | sed 's|refs/heads/||')
          
          # Check if PR already exists
          EXISTING_PR=$(gh pr list --base develop --head "$MAIN_BRANCH" --json state --jq '.[] | select(.state == "OPEN" or .state == "MERGED" or .state == "CLOSED")')
          
          if [ -n "$EXISTING_PR" ]; then
            echo "PR from $MAIN_BRANCH to develop already exists (open, closed, or merged). Skipping."
          else
            # Create the pull request
            PR_URL=$(gh pr create \
              --label "GitFlow" \
              --base develop \
              --head "$MAIN_BRANCH" \
              --title "Sync $MAIN_BRANCH to develop" \
              --body "Automated Pull Request to sync changes from 'main' to 'develop'.")

            # Extract PR number from URL
            PR_NUMBER=$(echo $PR_URL | sed 's/.*#\([0-9]*\)$/\1/')
            echo "Merge Pull Request: $PR_NUMBER"
  
            # Wait for the PR to be created and then merge it
            gh pr merge "$PR_NUMBER" --merge --auto
          fi


      # Feature to Develop
      - name: Create Pull Request for Feature to Develop
        if: github.ref_name && startsWith(github.ref, 'refs/heads/feature/')
        run: |
          # Extract branch name
          FEATURE_BRANCH=$(echo "${{ github.ref }}" | sed 's|refs/heads/||')
          
          # Check if PR already exists (open, closed, or merged)
          EXISTING_PR=$(gh pr list --base develop --head "$FEATURE_BRANCH" --json state --jq '.[] | select(.state == "OPEN" or .state == "MERGED" or .state == "CLOSED")')
          
          if [ -n "$EXISTING_PR" ]; then
            echo "PR from $FEATURE_BRANCH to develop already exists (open, closed, or merged). Skipping."
          else
            gh pr create \
              --label "GitFlow" \
              --base develop \
              --head "$FEATURE_BRANCH" \
              --title "Feature: Merge $FEATURE_BRANCH into Develop" \
              --body "This Pull Request merges the feature branch '$FEATURE_BRANCH' into 'develop'."
          fi

      # Hotfix to Main and Develop
      - name: Create Pull Request for Hotfix to Main and Develop
        if: github.ref_name && startsWith(github.ref, 'refs/heads/hotfix/')
        run: |
          # Extract branch name
          HOTFIX_BRANCH=$(echo "${{ github.ref }}" | sed 's|refs/heads/||')

          # Check if PR already exists (open, closed, or merged)
          EXISTING_PR=$(gh pr list --base develop --head "$HOTFIX_BRANCH" --json state --jq '.[] | select(.state == "OPEN" or .state == "MERGED" or .state == "CLOSED")')
          
          if [ -n "$EXISTING_PR" ]; then
            echo "PR from $HOTFIX_BRANCH to main already exists (open, closed, or merged). Skipping."
          else
            gh pr create \
              --label "GitFlow" \
              --base main \
              --head "$HOTFIX_BRANCH" \
              --title "Hotfix: Merge $HOTFIX_BRANCH into Main" \
              --body "This PR fixes critical issues in production."
          fi

          # PR for hotfix to develop
          if gh pr list --base develop --head "$HOTFIX_BRANCH" --json id | grep -q id; then
            echo "PR from $HOTFIX_BRANCH to develop already exists. Skipping."
          else
            gh pr create \
              --label "GitFlow" \
              --base develop \
              --head "$HOTFIX_BRANCH" \
              --title "Hotfix: Sync $HOTFIX_BRANCH with Develop" \
              --body "This PR ensures hotfix changes are merged into 'develop'."
          fi

      # Notifications (Optional)
      - name: Notify on Success
        if: success()
        run: echo "Gitflow automation completed successfully!"
