name: Open Pull Request from Main to Develop

on:
  push:
    branches:
      - main

jobs:
  update-branch:
    name: update-branch
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: app

    steps:
      - name: Check out code
        uses: actions/checkout@v4

      - name: Update branch
        uses: Logerfo/gitflow-action@0.0.4
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          dev: develop
          master: main
          label: GitFlow
          auto-merge: true
          require-merge: false