name: CI - Update Version Package.json

on:
  pull_request:
    types:
      - opened

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  tag:
    if: contains(github.head_ref, 'release/') && contains(github.base_ref, 'main')
    runs-on: ubuntu-latest
    outputs:
      tag: ${{ steps.tag.outputs.tag }}
    steps:
      - name: Extract branch tag
        id: tag
        run: |
          BRANCH=${{ github.head_ref }}
          TAG="${BRANCH//release\//}"
          echo $TAG
          echo "tag=$TAG" >> $GITHUB_OUTPUT

  update-version:
    needs:
      - tag
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: app
    env:
      TAG: ${{ needs.tag.outputs.tag }}
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Update version in package.json
        run: |
          jq '.version = "${{ env.TAG }}"' package.json > temp.json && mv temp.json package.json

      - name: Commit and push changes
        run: |
          git config --global user.name "GitHub Actions"
          git config --global user.email "github-actions@github.com"
          git add package.json
          git commit -m "chore: update version to v${{ env.TAG }} in package.json"
          
          # Configure o token de autenticação para o Git
          git remote set-url origin https://x-access-token:${{ secrets.GH_PAT }}@github.com/${{ github.repository }}.git
          git push origin ${{ github.head_ref }}

