name: CI-Update-Develop

on:
  push:
    branches: [ main ]

permissions:
  contents: read
  pull-requests: write

jobs:
  release:
    name: update-develop
    runs-on: ubuntu-22.04
    steps:
      - name: Update branch
        uses: Logerfo/gitflow-action@0.0.5
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          dev: develop
          master: main
          label: gitflow
          auto-merge: true
          require-merge: false
