name: Open Pull Request from Main to Develop

on:
  push:
    branches:
      - main

jobs:
  create-pull-request:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Create Pull Request
        uses: peter-evans/create-pull-request@v5
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          source-branch: main
          target-branch: develop
          title: "Sync main to develop"
          body: |
            This Pull Request was created automatically to sync changes from the `main` branch to the `develop` branch.
          branch: sync-main-to-develop
