name: Open Pull Request from Main to Develop

on:
  push:
    branches:
      - main

jobs:
  create-pull-request:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup GitHub CLI
        uses: docker://ghcr.io/cli/cli:latest

      - name: Open Pull Request
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          gh pr create \
            --base develop \
            --head main \
            --title "Sync main to develop" \
            --body "This PR was created automatically to sync changes from main to develop."
