name: Validate

on:
  pull_request:
    types:
      - opened
      - synchronize
    branches:
      - main
      - develop
      - "release/*"

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  validate:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: app

    if: ${{ github.event.pull_request.base.ref != 'develop' || github.event.pull_request.head.ref != 'main' }}

    steps:
      - name: Check out code
        uses: actions/checkout@v4

      - name: Set up Node
        uses: actions/setup-node@v4
        with:
          node-version: 22

      - uses: actions/cache@v3
        with:
          path: '**/node_modules'
          key: ${{ runner.os }}-modules-${{ hashFiles('**/yarn.lock') }}

      - name: Install dependencies
        run: yarn install

      - name: Lint
        run: yarn lint

      - name: Format
        run: yarn format

      - name: Build
        run: yarn build

      - name: Test
        run: yarn test:coverage

      - name: Create badges
        if: contains(github.head_ref, 'release/') && contains(github.base_ref, 'main')
        run: yarn readme:coverage

      - name: Authenticate GitHub CLI
        if: contains(github.head_ref, 'release/') && contains(github.base_ref, 'main')
        run: echo "${{ secrets.GH_PAT }}" | gh auth login --with-token

      - name: Commit and push changes
        if: contains(github.head_ref, 'release/') && contains(github.base_ref, 'main')
        run: |
          git config --global user.name "GitHub Actions"
          git config --global user.email "github-actions@github.com"

          git checkout -B ${{ github.head_ref }} || git checkout -b ${{ github.head_ref }}

          git add .
          git commit -m "docs: test coverage badges update"

          git pull origin ${{ github.head_ref }} --rebase

          git push https://x-access-token:${{ secrets.GH_PAT }}@github.com/${{ github.repository }}.git ${{ github.head_ref }}
