name: Validate

on:
  pull_request:
    types:
      - opened
      - synchronize
    branches:
      - main
      - develop
      - "release/*"

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  validate:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: app

    if: ${{ github.event.pull_request.base.ref != 'develop' || github.event.pull_request.head.ref != 'main' }}

    steps:
      - name: Check out code
        uses: actions/checkout@v4

      - name: Set up Node
        uses: actions/setup-node@v4
        with:
          node-version: 22

      - uses: actions/cache@v3
        with:
          path: '**/node_modules'
          key: ${{ runner.os }}-modules-${{ hashFiles('**/yarn.lock') }}

      - name: Install dependencies
        run: yarn install

      - name: Lint
        run: yarn lint

      - name: Format
        run: yarn format

      - name: Check for 'test:' prefix in commit messages
        id: check_commits
        uses: actions/github-script@v7.0.1
        with:
          script: |
            const pr = github.event.pull_request;
            const commits = await github.rest.pulls.listCommits({
              owner: pr.head.repo.owner.login,
              repo: pr.head.repo.name,
              pull_number: pr.number,
            });
            
            echo "Commits prefix: $commits"
          
            const hasTestPrefix = commits.data.some(commit => commit.commit.message.startsWith('test:'));
            
            echo "Commit prefix: $hasTestPrefix"
            
            return hasTestPrefix;

      - name: Test
        if: steps.check_commits.outputs.result == 'true'
        run: yarn test

      - name: Build
        run: yarn build