name: Validate

on:
  pull_request:
    types:
      - opened
      - synchronize
    branches:
      - main
      - develop
      - "release/*"

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  validate:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: app

    if: ${{ github.event.pull_request.base.ref != 'develop' || github.event.pull_request.head.ref != 'main' }}

    steps:
      - name: Check out code
        uses: actions/checkout@v4

      - name: Set up Node
        uses: actions/setup-node@v4
        with:
          node-version: 22

      - uses: actions/cache@v3
        with:
          path: '**/node_modules'
          key: ${{ runner.os }}-modules-${{ hashFiles('**/yarn.lock') }}

      - name: Install dependencies
        run: yarn install

      - name: Lint
        run: yarn lint

      - name: Format
        run: yarn format

      - name: Build
        run: yarn build

      - name: Test
        run: yarn test:coverage

      - name: Create badges
        if: contains(github.head_ref, 'release/') && contains(github.base_ref, 'main')
        run: yarn readme:coverage

      - name: Commit and push changes
        if: contains(github.head_ref, 'release/') && contains(github.base_ref, 'main')
        uses: devops-infra/action-commit-push@master
        with:
          github_token: ${{ secrets.GH_PAT }}
          commit_message: "docs: test coverage badges update"
