name: Validate

on:
  pull_request:
    types:
      - opened
      - synchronize
    branches:
      - main
      - develop
      - "release/*"

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  validate:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: app

    steps:
      - name: Check out code
        uses: actions/checkout@v4

      - name: Set up Node
        uses: actions/setup-node@v4
        with:
          node-version: 22

      - uses: actions/cache@v3
        with:
          path: '**/node_modules'
          key: ${{ runner.os }}-modules-${{ hashFiles('**/yarn.lock') }}


      - name: Fetch all branches
        run: git fetch --all

      - name: Get pull request commits
        id: pr-commits
        run: |
          # Obter a lista de commits do pull request
          PR_COMMITS=$(git log origin/${{ github.event.pull_request.base.ref }}..HEAD --oneline)
          echo "Commits in the PR: $PR_COMMITS"
          echo "PR_COMMITS=$PR_COMMITS" >> $GITHUB_ENV

      - name: Check commit prefix
        id: check-commit
        run: |
          COMMIT_MSG=$PR_COMMITS
          echo "Commit message: $COMMIT_MSG"
          echo "run-tests=false" >> $GITHUB_ENV
          echo "run-lint=false" >> $GITHUB_ENV
    
          while IFS= read -r COMMIT; do
            echo "Checking commit: $COMMIT"
            if echo "$COMMIT" | grep -qE '^(feat|fix|chore|refactor|test)\:'; then
              echo "✅ Commit message follows convention."
              echo "run-lint=true" >> $GITHUB_ENV
            fi
            if echo "$COMMIT" | grep -qE '^test\:'; then
              echo "✅ Test commit detected."
              echo "run-tests=true" >> $GITHUB_ENV
            fi
          done <<< "$PR_COMMITS"

      - name: Install dependencies
        if: ${{ env.run-lint == 'true' || env.run-tests == 'true' }}
        run: yarn install

      - name: Lint
        if: ${{ env.run-lint == 'true' }}
        run: yarn lint

      - name: Format
        if: ${{ env.run-lint == 'true' }}
        run: yarn format

      - name: Test
        if: ${{ env.run-tests == 'true' }}
        run: yarn test

      - name: Build
        if: ${{ env.run-lint == 'true' }}
        run: yarn build